# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jairfrancesco/Imágenes/opensurf/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jairfrancesco/Imágenes/opensurf/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jairfrancesco/Imágenes/opensurf/src/CMakeFiles /home/jairfrancesco/Imágenes/opensurf/src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jairfrancesco/Imágenes/opensurf/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named surf

# Build rule for target.
surf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 surf
.PHONY : surf

# fast build rule for target.
surf/fast:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/build
.PHONY : surf/fast

#=============================================================================
# Target rules for targets named surffeat

# Build rule for target.
surffeat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 surffeat
.PHONY : surffeat

# fast build rule for target.
surffeat/fast:
	$(MAKE) -f CMakeFiles/surffeat.dir/build.make CMakeFiles/surffeat.dir/build
.PHONY : surffeat/fast

# target to build an object file
fasthessian.o:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/fasthessian.o
.PHONY : fasthessian.o

# target to preprocess a source file
fasthessian.i:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/fasthessian.i
.PHONY : fasthessian.i

# target to generate assembly for a file
fasthessian.s:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/fasthessian.s
.PHONY : fasthessian.s

# target to build an object file
integral.o:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/integral.o
.PHONY : integral.o

# target to preprocess a source file
integral.i:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/integral.i
.PHONY : integral.i

# target to generate assembly for a file
integral.s:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/integral.s
.PHONY : integral.s

# target to build an object file
ipoint.o:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/ipoint.o
.PHONY : ipoint.o

# target to preprocess a source file
ipoint.i:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/ipoint.i
.PHONY : ipoint.i

# target to generate assembly for a file
ipoint.s:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/ipoint.s
.PHONY : ipoint.s

# target to build an object file
main.o:
	$(MAKE) -f CMakeFiles/surffeat.dir/build.make CMakeFiles/surffeat.dir/main.o
.PHONY : main.o

# target to preprocess a source file
main.i:
	$(MAKE) -f CMakeFiles/surffeat.dir/build.make CMakeFiles/surffeat.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) -f CMakeFiles/surffeat.dir/build.make CMakeFiles/surffeat.dir/main.s
.PHONY : main.s

# target to build an object file
surf.o:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/surf.o
.PHONY : surf.o

# target to preprocess a source file
surf.i:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/surf.i
.PHONY : surf.i

# target to generate assembly for a file
surf.s:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/surf.s
.PHONY : surf.s

# target to build an object file
utils.o:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/utils.o
.PHONY : utils.o

# target to preprocess a source file
utils.i:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/utils.i
.PHONY : utils.i

# target to generate assembly for a file
utils.s:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/utils.s
.PHONY : utils.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... surf"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... surffeat"
	@echo "... fasthessian.o"
	@echo "... fasthessian.i"
	@echo "... fasthessian.s"
	@echo "... integral.o"
	@echo "... integral.i"
	@echo "... integral.s"
	@echo "... ipoint.o"
	@echo "... ipoint.i"
	@echo "... ipoint.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... surf.o"
	@echo "... surf.i"
	@echo "... surf.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

