# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jairfrancesco/OpenSurf

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jairfrancesco/OpenSurf

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jairfrancesco/OpenSurf/CMakeFiles /home/jairfrancesco/OpenSurf/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jairfrancesco/OpenSurf/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named surf

# Build rule for target.
surf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 surf
.PHONY : surf

# fast build rule for target.
surf/fast:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/build
.PHONY : surf/fast

#=============================================================================
# Target rules for targets named surffeat

# Build rule for target.
surffeat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 surffeat
.PHONY : surffeat

# fast build rule for target.
surffeat/fast:
	$(MAKE) -f CMakeFiles/surffeat.dir/build.make CMakeFiles/surffeat.dir/build
.PHONY : surffeat/fast

ipoint.o: ipoint.cpp.o
.PHONY : ipoint.o

# target to build an object file
ipoint.cpp.o:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/ipoint.cpp.o
.PHONY : ipoint.cpp.o

ipoint.i: ipoint.cpp.i
.PHONY : ipoint.i

# target to preprocess a source file
ipoint.cpp.i:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/ipoint.cpp.i
.PHONY : ipoint.cpp.i

ipoint.s: ipoint.cpp.s
.PHONY : ipoint.s

# target to generate assembly for a file
ipoint.cpp.s:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/ipoint.cpp.s
.PHONY : ipoint.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/surffeat.dir/build.make CMakeFiles/surffeat.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/surffeat.dir/build.make CMakeFiles/surffeat.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/surffeat.dir/build.make CMakeFiles/surffeat.dir/main.cpp.s
.PHONY : main.cpp.s

surf.o: surf.cpp.o
.PHONY : surf.o

# target to build an object file
surf.cpp.o:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/surf.cpp.o
.PHONY : surf.cpp.o

surf.i: surf.cpp.i
.PHONY : surf.i

# target to preprocess a source file
surf.cpp.i:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/surf.cpp.i
.PHONY : surf.cpp.i

surf.s: surf.cpp.s
.PHONY : surf.s

# target to generate assembly for a file
surf.cpp.s:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/surf.cpp.s
.PHONY : surf.cpp.s

utils.o: utils.cpp.o
.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i
.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s
.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... surf"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... surffeat"
	@echo "... ipoint.o"
	@echo "... ipoint.i"
	@echo "... ipoint.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... surf.o"
	@echo "... surf.i"
	@echo "... surf.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

